### ISSUE TITLE
git-scripts cannot authenticate if user has 2FA

### ISSUE THREAD

**Issue by joshterrell805** [iFixit/git-scripts#125]
https://github.com/iFixit/git-scripts/blob/master/lib/github.rb#L61

This function doesn't have support for two-factor authentication. Relevant output from performing a feature finish:
```
Authorizing...
github username: joshterrell805
github password:
===============================================================================
Github API Error
GET https://api.github.com/authorizations: 401: Must specify two-factor
authentication OTP code.
```

**Comment by copperwall** [comment]
It looks like the solution to this is to ask the user to generate the one time OTP token, prompt them for it, and then send it with the `X-GitHub-OTP` header.

Or we could at least prompt the user to create a token and store it in their `.gitconfig`.

**Comment by marczych** [comment]
> Or we could at least prompt the user to create a token and store it in their .gitconfig.

This is probably the best option or we can investigate CLI 2FA options.

**Comment by danielbeardsley** [comment]
Yeah, I'd vote for bailing on u/p and only asking for a token. You can create them from the web now, so it's not a big hurdle.
