### ISSUE TITLE
Docs need to be updated

### ISSUE THREAD

**Issue by MutantFreak** [iFixit/git-scripts#134]
The documentation for this repo needs to be updated. It still describes a two branch workflow, even though iFixit moved to a single branch workflow a few months ago.

**Comment by davidrans** [comment]
All of our code still supports a two-branch workflow. Do we want to get rid of that functionality just because we aren't using the `hotfix` command anymore?

**Comment by marczych** [comment]
Removing `hotfix` would certainly clean out some old cruft but I don't know if it's worth the trouble especially if it's just because _we_ have stopped using `hotfix`. @danielbeardsley?

**Comment by danielbeardsley** [comment]
Agreed. Let's close this, just cause we stopped using it doesn't mean we should drop the feature or the docs.
