### ISSUE TITLE
Transfer fastpass label from issues to pulls

### ISSUE THREAD

**Issue by saltaverde** [iFixit/git-scripts#150]
Background
--
Would be helpful to further enhance `feature finish` to apply the fastpass label to the pull if the issue is a fastpass, otherwise it has to be added manually, especially once iFixit/pulldasher#133 goes through.

**Comment by danielbeardsley** [comment]
I don't think we care very much anymore, there's not so much noise that import things are drown out. It hasn't been a problem as of late.
