### ISSUE TITLE
`feature` doesn't work in Ruby repos

### ISSUE THREAD

**Issue by djmetzle** [iFixit/git-scripts#157]
The irony!

Repo:
```sh
$ mkdir arbitrary_dir
$ feature
# works fine
$ touch Gemfile
$ feature 
# BOOM
```

CC @danielbeardsley

**Comment by danielbeardsley** [comment]
Ok I agree, this is dum. Let's fix it.

**Comment by djmetzle** [comment]
Merging this: https://github.com/iFixit/server-templates/pull/2263

Means that server-templates is now incompatible with `feature` until this is fixed.

**Comment by djmetzle** [comment]
@addison-grant Did you have any insights into the exact problem here?

**Comment by addison-grant** [comment]
Not at this time. I'll have to dig some more.

**Comment by djmetzle** [comment]
Any progress here? Who "owns" this?

![image](https://user-images.githubusercontent.com/6876047/65642162-75c4b600-dfa3-11e9-8528-ac8f5bb66c97.png)

**Comment by danielbeardsley** [comment]
We all own it :-)

**Comment by danielbeardsley** [comment]
Fixed with #158

**Comment by addison-grant** [comment]
@danielbeardsley, awesome!

**Comment by djmetzle** [comment]
This went away for a short while but now its back. Reopening...

**Comment by djmetzle** [comment]
I suspect the bug was inflicted again sometime after #158?

![image](https://user-images.githubusercontent.com/6876047/79909397-bff30600-83d1-11ea-9fe6-6b7d65c5409c.png)

**Comment by danielbeardsley** [comment]
I poured a couple of hours into it on several occasions and couldn't make it work. Felt quite defeated. Everything about rubygems says it was loading the gems from the normal system-level place, but yet in practice it was still being affected by the local Gemfile in the CWD.

I eventually made a pull to do it the seemingly standard way (which didn't seem to change behavior) and gave up.

**Comment by djmetzle** [comment]
Bump. Still a problem.

**Comment by djmetzle** [comment]
I think we should mostly prefer to use the `gh` [github cli ](https://cli.github.com/) as a replacement for most of the features of `feature`. Closing.
